# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edvard Busck-Nielsen - Portfolio
email: edvard1807@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Edvard Busck-Nielsen and I've had a interest in technology and creating for as long as I can remember
  and I have been programming for about 6 years and would like to make it my job.
  I enjoy creating and solving problems because nothing else gives you that special feeling of success!
  I have thought myself HTML5, Python, Shell Script and Linux, as well as a lot of different tools and programs.
  There is nothing better than to create something new and experiment with new stuff, I'm constantly crowing and I enjoy learning about new things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://buscedv.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_link:  https://github.com/Buscedv
instagram_link:  https://instagram.com/Buscedv
devrant_link: https://devrant.com/users/buscedv
email_link: mailto:edvard1807@gmail.com

username: buscedv

year: 2019
logo: logo.png

collections:
    skills:
    portfolio:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
