[[redirects]]
  from = "https://edvard.io"
  to = "https://edvard.dev"
  status = 301
  force = false
[[redirects]]
  from = "https://edvard.netlify.app"
  to = "https://edvard.dev"
  status = 301
  force = false
# Old paths to new domain
[[redirects]]
  from = "https://edvard.io/cookies"
  to = "https://edvard.dev/cookies"
  status = 301
  force = false
[[redirects]]
  from = "https://edvard.io/privacy"
  to = "https://edvard.dev/privacy"
  status = 301
  force = false
